// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyShippingPlatform.Infrastructure.Persistence;

#nullable disable

namespace MyShippingPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyShippingPlatform.Domain.Entities.AIAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DeclaredValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ExtractedHsCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsReviewedByHuman")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RawAgentOutputJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("longtext");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<string>("RiskReasoning")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("AIAuditRecords");
                });

            modelBuilder.Entity("MyShippingPlatform.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConsigneeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShipperName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("MyShippingPlatform.Domain.Entities.AIAuditRecord", b =>
                {
                    b.HasOne("MyShippingPlatform.Domain.Entities.Shipment", "Shipment")
                        .WithMany("AuditRecords")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("MyShippingPlatform.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("AuditRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
